build-linux:
  stage: build
  before_script:
  #find current version in cmakelists.txt
  - VERSION=$(grep -oP 'project\(plants VERSION \K[0-9]+\.[0-9]+\.[0-9]+' CMakeLists.txt)
  script:
  - apt-get update --yes
  - apt-get install --yes cmake
  - cmake -B build
  - cmake --build build 
  - cp out/Tests_Linux_${VERSION} tests/runtest
  - mv README.md out/README_${VERSION}.md
  - cd tests
  - ./runtest
  artifacts:
    paths:
      - out
  when: on_success

documentation:
  image: alpine
  stage: build
  script:
  - apk update && apk add doxygen graphviz ttf-freefont
  - ls
  - doxygen Doxyfile
  - mv html/ public/
  artifacts:
    paths:
    - public
  when: on_success


build-win:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'
      when: always
    - when: never
  tags: 
    - windows
  before_script:
#    - choco install -y cmake #already installed
    - $env:Path += ';C:\Program Files\CMake\bin'
    - choco install mingw -y --version=12.2.0
    - $env:Path += ';C:\Program Files\MinGW-w64\bin'
  stage: build
  script:
    - cmake --help
    - cmake -B build -G "MinGW Makefiles"
    - cmake --build build
  # '& "out/Tests_Windows_${VERSION}.exe" '
  #  - '& "out/Model_Windows_${VERSION}.exe" -f \tests\test.json'
  artifacts:
    paths:
      - out
  when: on_success
